### ISSUE TITLE
no-unused-import plugin?

### ISSUE THREAD

**Issue by EcutDavid** [css-modules/postcss-icss-values#111]
Hey,

I didn't find any clue that this postcss plugin already exist, but do we have some thing that will yield an error or warning for 
```
----content of a.css----
@value b from "b";

@value c from "c";

.d {
    color: b;
}
----end of a.css----
```

```
a.css
3:1:  Imported values must be used (no-unused-import): c
```

Thanks!

**Comment by kumarharsh** [comment]
Even I'd like to see this implemented. Although I get a feeling it's not possible because literally **any** file can import any variables from any other file without any explicit `export` statement. Hence the linter would need to analyse the whole codebase to give any unused import error.

**Comment by EcutDavid** [comment]
Agree with what @kumarharsh said.
