### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ajkl2533** [css-modules/postcss-icss-values#114]
Hi is it possible to add LICENSE file in this repo, right now it is proprietary code and cannot be used by anyone. MIT license requires LICENSE file in repo and also in NPM distribution package.

**Comment by alexander-akait** [comment]
@ajkl2533 PR welcome

**Comment by patricksmms** [comment]
@evilebottnawi, can you please also publish it to npm? Thanks!

**Comment by alexander-akait** [comment]
@patricksmms WIP

**Comment by alexander-akait** [comment]
@patricksmms done in https://github.com/css-modules/postcss-icss-values/releases/tag/v2.0.2 (maybe need backport in `1.x.x` version, feel free to send a PR)

**Comment by patricksmms** [comment]
@evilebottnawi, thanks a lot!
