### ISSUE TITLE
Importing value results in undefined

### ISSUE THREAD

**Issue by dfala** [css-modules/postcss-icss-values#16]
Followed steps on README file, but `primary` and `secondary` get a value of `undefined` on _my-component.css._

**Comment by margalit** [comment]
For anyone else experiencing similar issues in webpack be sure to add 
`&importLoaders=1` to your css loader string as per the [PostCSS loader readme](https://github.com/webpack/css-loader#css-modules). For example:

`{
      test: /\.css$/,
      loader: 'style!css?modules&localIdentName=[name]---[local]---[hash:base64:5]&importLoaders=1!postcss-loader'
    }`

**Comment by haohcraft** [comment]
@margalit  whats the `importLoaders=1` for?

**Comment by haohcraft** [comment]
Found an explanation from [here](https://github.com/webpack/css-loader/issues/228)
