### ISSUE TITLE
Request: Use JSON or JavaScript modules

### ISSUE THREAD

**Issue by kevinSuttle** [css-modules/postcss-icss-values#25]
Is it possible to supply JSON values to share between web, native, etc? 
Something like https://viget.com/extend/sharing-data-between-sass-and-javascript-with-json?

**Comment by madyankin** [comment]
@kevinSuttle  There is a PostCSS plugin for this https://github.com/postcss/postcss-simple-vars

**Comment by kevinSuttle** [comment]
From what I can tell, that plugin only supports basic `module.exports`. A more complicated structure wouldn't work it seems. 

Something like https://github.com/pascalduez/postcss-map/issues/76

I opened an issue there just in case. Thanks. https://github.com/postcss/postcss-simple-vars/issues/47
