### ISSUE TITLE
Modules values default value

### ISSUE THREAD

**Issue by alansouzati** [css-modules/postcss-icss-values#53]
I tried to find in the README page how to assign a default value to a variable, but I could not find it in the docs.

This is more or less what I'm trying to achieve:

``` css
@value defaultFontSize from './font.css';
@value h1FontSize: defaultFontSize from '$(themePath)/shared/font.css';
```

In this case, if the fonts import from the theme does not have h1FontSize, I would assign the default value instead.

**Comment by TrySound** [comment]
@alansouzati Aliases like in es modules
```
@value defaultFontSize as h1FontSize from '$(themePath)/shared/font.css';
```
