### ISSUE TITLE
the lib folder has been removed on version 1.2.1

### ISSUE THREAD

**Issue by iqingting** [css-modules/postcss-icss-values#63]
And this caused postcss-modules-values is not a PostCSS plugin if babel-loader exclude node_modules directory.

I guss.

**Comment by rguanghui** [comment]
And this caused `postcss-modules-values` is not a PostCSS plugin if `babel-loader` exclude node_modules directory.

I guss.

**Comment by geelen** [comment]
Thanks for raising. Pushed the latest tag back to v1.1.3 until this is fixed. Discussion in #62
