### ISSUE TITLE
Values are not exported..

### ISSUE THREAD

**Issue by delijah** [css-modules/postcss-icss-values#67]
..when using #-color as a value and using node-sass.

I am using sass and css modules and webpack. If i define the following values..

```
@value border-color #aaa
@value soft-border-color rgb(204, 204, 204)
```

..i will get the second one as an exported value, but i'll not get border-color. It looks like node-sass is not translating the first value (as soon it is a color definition with a #).

Resulting css (after node-sass, before postcss-modules-values):
`@value border-color;\n@value soft-border-color rgb(204, 204, 204) {}`

I am a little lost. Is it a postcss-modules-values issue? Or sass-loader, or node-sass, or libsass?...

Thanks for help...

**Comment by delijah** [comment]
Also related to https://github.com/css-modules/css-modules/issues/170.

Why?

If i could place all the value definitions in a css file and import it from/into a sass file, this issue would not exist.

**Comment by delijah** [comment]
Someone here to help?

**Comment by delijah** [comment]
No one here?

**Comment by joeybaker** [comment]
Hi @delijah, I'm not a sass user, so I can't really help, but we have a new chat room where I know folks do use sass. We're trying to get organized and give this project better maintance, but in the meantime, you could try asking there: https://discord.gg/m2QBEZ5
