### ISSUE TITLE
Is it possible to use webpack resolution aliases when importing values?

### ISSUE THREAD

**Issue by mattkauffman23** [css-modules/postcss-icss-values#80]
We use webpack aliases to simplify importing modules in our es6 code. We'd like to do something similar when importing values in our css files. Is there a way to do either absolute paths for value imports (considering the project as the root for the path) or get the value import to check some sort of configuration, similar to how aliasing works in webpack?

**Comment by rpunkfu** [comment]
It is, if you configure aliases in webpack config it works in both js and css

**Comment by mattkauffman23** [comment]
@rpunkfu sorry just getting back to this. Took another look and I was missing `css` in `extensions` part of `resolve` in my webpack config. Apologies for the trouble. Closing.

**Comment by rpunkfu** [comment]
No need to be sorry haha, glad you worked it out ;)
