### ISSUE TITLE
importing value from relative path

### ISSUE THREAD

**Issue by coot** [css-modules/postcss-icss-values#99]
If I import from the same directory everything works fine, but if I import from a parent directory things do not work:
```
@value parentValue from "../colors.css";
@value aValue from "./a.css";

.title {
  color: parentValue;
  background: aValue;
}
```

The `color` property will not be set.  I use `css-modulesify` which is currently using `postcss-5.1.2`.

**Comment by TrySound** [comment]
It'e the problem with css-modulesify. Report there please.
